// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkYWSev314vzt4X99gF8CARayIm1MU4w4',
    appId: '1:178245391290:web:277981420151aae6700383',
    messagingSenderId: '178245391290',
    projectId: 'bwa-hotelio-f1e47',
    authDomain: 'bwa-hotelio-f1e47.firebaseapp.com',
    storageBucket: 'bwa-hotelio-f1e47.appspot.com',
    measurementId: 'G-QR7Q8T8DR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vAyOcT35o0rbKAPl3yujpOM0Fb32Dtg',
    appId: '1:178245391290:android:97c4e4a2de0420da700383',
    messagingSenderId: '178245391290',
    projectId: 'bwa-hotelio-f1e47',
    storageBucket: 'bwa-hotelio-f1e47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADzQcXUdCLXU8L7YfAsFvFX75T5BiYVpY',
    appId: '1:178245391290:ios:16df522a813f96b8700383',
    messagingSenderId: '178245391290',
    projectId: 'bwa-hotelio-f1e47',
    storageBucket: 'bwa-hotelio-f1e47.appspot.com',
    iosClientId: '178245391290-revcf2fn270i4q76078hig01lup0s11s.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADzQcXUdCLXU8L7YfAsFvFX75T5BiYVpY',
    appId: '1:178245391290:ios:523a5cdcb80b5792700383',
    messagingSenderId: '178245391290',
    projectId: 'bwa-hotelio-f1e47',
    storageBucket: 'bwa-hotelio-f1e47.appspot.com',
    iosClientId: '178245391290-3rlqguthbfqdnlcd0m5aammm1p5cf2ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio.RunnerTests',
  );
}
